package calculadora;

public class TelaCalculadora extends javax.swing.JFrame {

    public TelaCalculadora() {
        initComponents();
    }
    String r, r2, r3, re; 
    Calculadora c = new Calculadora();
    String tipo, numero;
    boolean ve;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        buttonVirgula = new java.awt.Button();
        buttonNum9 = new java.awt.Button();
        buttonResultado = new java.awt.Button();
        buttonNum0 = new java.awt.Button();
        button20 = new java.awt.Button();
        buttonMais = new java.awt.Button();
        buttonNum3 = new java.awt.Button();
        buttonNum2 = new java.awt.Button();
        buttonNum1 = new java.awt.Button();
        buttonMenos = new java.awt.Button();
        buttonNum6 = new java.awt.Button();
        buttonNum5 = new java.awt.Button();
        buttonNum4 = new java.awt.Button();
        buttonMultiplicacao = new java.awt.Button();
        buttonNum8 = new java.awt.Button();
        buttonApagarTudo = new java.awt.Button();
        buttonNum7 = new java.awt.Button();
        buttonDivisao = new java.awt.Button();
        buttonapagarTexto2 = new java.awt.Button();
        buttonApagarTexto = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(390, 620));
        setSize(new java.awt.Dimension(390, 620));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 70, 180, 30);

        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 70, 334, 51);

        buttonVirgula.setBackground(new java.awt.Color(204, 204, 204));
        buttonVirgula.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonVirgula.setLabel(",");
        buttonVirgula.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonVirgula.setName(""); // NOI18N
        buttonVirgula.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonVirgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonVirgulaMouseClicked(evt);
            }
        });
        getContentPane().add(buttonVirgula);
        buttonVirgula.setBounds(198, 492, 70, 70);

        buttonNum9.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum9.setLabel("9");
        buttonNum9.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum9.setName(""); // NOI18N
        buttonNum9.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum9MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum9);
        buttonNum9.setBounds(196, 230, 70, 70);

        buttonResultado.setBackground(new java.awt.Color(255, 255, 0));
        buttonResultado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonResultado.setLabel("=");
        buttonResultado.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonResultado.setName(""); // NOI18N
        buttonResultado.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonResultadoMouseClicked(evt);
            }
        });
        getContentPane().add(buttonResultado);
        buttonResultado.setBounds(285, 492, 70, 70);

        buttonNum0.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum0.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum0.setLabel("0");
        buttonNum0.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum0.setName(""); // NOI18N
        buttonNum0.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum0MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum0);
        buttonNum0.setBounds(110, 492, 70, 70);

        button20.setBackground(new java.awt.Color(204, 204, 204));
        button20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button20.setLabel("%");
        button20.setMinimumSize(new java.awt.Dimension(70, 70));
        button20.setName(""); // NOI18N
        button20.setPreferredSize(new java.awt.Dimension(1000, 24));
        getContentPane().add(button20);
        button20.setBounds(20, 492, 70, 70);

        buttonMais.setBackground(new java.awt.Color(204, 204, 204));
        buttonMais.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonMais.setLabel("+");
        buttonMais.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonMais.setName(""); // NOI18N
        buttonMais.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMaisMouseClicked(evt);
            }
        });
        getContentPane().add(buttonMais);
        buttonMais.setBounds(285, 405, 70, 70);

        buttonNum3.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum3.setLabel("3");
        buttonNum3.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum3.setName(""); // NOI18N
        buttonNum3.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum3MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum3);
        buttonNum3.setBounds(198, 405, 70, 70);

        buttonNum2.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum2.setLabel("2");
        buttonNum2.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum2.setName(""); // NOI18N
        buttonNum2.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum2MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum2);
        buttonNum2.setBounds(110, 405, 70, 70);

        buttonNum1.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum1.setLabel("1");
        buttonNum1.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum1.setName(""); // NOI18N
        buttonNum1.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum1MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum1);
        buttonNum1.setBounds(20, 405, 70, 70);

        buttonMenos.setBackground(new java.awt.Color(204, 204, 204));
        buttonMenos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonMenos.setLabel("-");
        buttonMenos.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonMenos.setName(""); // NOI18N
        buttonMenos.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenosMouseClicked(evt);
            }
        });
        getContentPane().add(buttonMenos);
        buttonMenos.setBounds(285, 317, 70, 70);

        buttonNum6.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum6.setLabel("6");
        buttonNum6.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum6.setName(""); // NOI18N
        buttonNum6.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum6MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum6);
        buttonNum6.setBounds(198, 317, 70, 70);

        buttonNum5.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum5.setLabel("5");
        buttonNum5.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum5.setName(""); // NOI18N
        buttonNum5.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum5MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum5);
        buttonNum5.setBounds(110, 317, 70, 70);

        buttonNum4.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum4.setLabel("4");
        buttonNum4.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum4.setName(""); // NOI18N
        buttonNum4.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum4MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum4);
        buttonNum4.setBounds(20, 317, 70, 70);

        buttonMultiplicacao.setBackground(new java.awt.Color(204, 204, 204));
        buttonMultiplicacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonMultiplicacao.setLabel("X");
        buttonMultiplicacao.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonMultiplicacao.setName(""); // NOI18N
        buttonMultiplicacao.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonMultiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMultiplicacaoMouseClicked(evt);
            }
        });
        getContentPane().add(buttonMultiplicacao);
        buttonMultiplicacao.setBounds(285, 230, 70, 70);

        buttonNum8.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum8.setLabel("8");
        buttonNum8.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum8.setName(""); // NOI18N
        buttonNum8.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum8MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum8);
        buttonNum8.setBounds(110, 230, 70, 70);

        buttonApagarTudo.setBackground(new java.awt.Color(255, 255, 0));
        buttonApagarTudo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonApagarTudo.setLabel("CE");
        buttonApagarTudo.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonApagarTudo.setName(""); // NOI18N
        buttonApagarTudo.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonApagarTudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonApagarTudoMouseClicked(evt);
            }
        });
        getContentPane().add(buttonApagarTudo);
        buttonApagarTudo.setBounds(20, 140, 70, 70);

        buttonNum7.setBackground(new java.awt.Color(153, 153, 153));
        buttonNum7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonNum7.setLabel("7");
        buttonNum7.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonNum7.setName(""); // NOI18N
        buttonNum7.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonNum7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNum7MouseClicked(evt);
            }
        });
        getContentPane().add(buttonNum7);
        buttonNum7.setBounds(20, 230, 70, 70);

        buttonDivisao.setBackground(new java.awt.Color(204, 204, 204));
        buttonDivisao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonDivisao.setLabel("/");
        buttonDivisao.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonDivisao.setName(""); // NOI18N
        buttonDivisao.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDivisaoMouseClicked(evt);
            }
        });
        getContentPane().add(buttonDivisao);
        buttonDivisao.setBounds(285, 140, 70, 70);

        buttonapagarTexto2.setBackground(new java.awt.Color(204, 204, 204));
        buttonapagarTexto2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonapagarTexto2.setLabel("X<=");
        buttonapagarTexto2.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonapagarTexto2.setName(""); // NOI18N
        buttonapagarTexto2.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonapagarTexto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonapagarTexto2MouseClicked(evt);
            }
        });
        getContentPane().add(buttonapagarTexto2);
        buttonapagarTexto2.setBounds(196, 140, 70, 70);

        buttonApagarTexto.setBackground(new java.awt.Color(204, 204, 204));
        buttonApagarTexto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonApagarTexto.setLabel("C");
        buttonApagarTexto.setMinimumSize(new java.awt.Dimension(70, 70));
        buttonApagarTexto.setName(""); // NOI18N
        buttonApagarTexto.setPreferredSize(new java.awt.Dimension(1000, 24));
        buttonApagarTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonApagarTextoMouseClicked(evt);
            }
        });
        getContentPane().add(buttonApagarTexto);
        buttonApagarTexto.setBounds(110, 140, 70, 70);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calculadora");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 137, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo-preto-background (1).png"))); // NOI18N
        jLabel3.setDoubleBuffered(true);
        jLabel3.setFocusCycleRoot(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, 0, 380, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void buttonNum0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum0MouseClicked
        colocarNumero("0");
        Mostrar(r);
    }//GEN-LAST:event_buttonNum0MouseClicked

    private void buttonNum1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum1MouseClicked
        colocarNumero("1");
        numero = "1";
        Mostrar(r);
    }//GEN-LAST:event_buttonNum1MouseClicked

    private void buttonNum2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum2MouseClicked
        colocarNumero("2");
        numero = "2";
        Mostrar(r);
    }//GEN-LAST:event_buttonNum2MouseClicked

    private void buttonNum3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum3MouseClicked
        colocarNumero("3");
        numero = "3";
        Mostrar(r);
    }//GEN-LAST:event_buttonNum3MouseClicked

    private void buttonNum4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum4MouseClicked
        colocarNumero("4");
        numero = "4";
        Mostrar(r);
    }//GEN-LAST:event_buttonNum4MouseClicked

    private void buttonNum5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum5MouseClicked
        colocarNumero("5");
        numero = "5";
        Mostrar(r);
    }//GEN-LAST:event_buttonNum5MouseClicked

    private void buttonNum6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum6MouseClicked
        colocarNumero("6");
        numero = "6";
        Mostrar(r);
    }//GEN-LAST:event_buttonNum6MouseClicked

    private void buttonNum7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum7MouseClicked
        colocarNumero("7");
        numero = "7";
        Mostrar(r);
    }//GEN-LAST:event_buttonNum7MouseClicked

    private void buttonNum8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum8MouseClicked
        colocarNumero("8");
        numero = "8";        
        Mostrar(r);
    }//GEN-LAST:event_buttonNum8MouseClicked

    private void buttonNum9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNum9MouseClicked
        colocarNumero("9");
        numero = "9";
        Mostrar(r);
    }//GEN-LAST:event_buttonNum9MouseClicked

    private void buttonVirgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVirgulaMouseClicked
        colocarNumero(".");
        Mostrar(r);
    }//GEN-LAST:event_buttonVirgulaMouseClicked

    private void buttonApagarTudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonApagarTudoMouseClicked
        jTextField1.setText("0");
        r = null;
        ve = false;
        c.limpar();
        jLabel2.setText("");
    }//GEN-LAST:event_buttonApagarTudoMouseClicked

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        Iniciar();
    }//GEN-LAST:event_jTextField1FocusGained

    private void buttonMaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMaisMouseClicked
        ve = true;
        colocarNumero(" + ");
        tipo = "\\+";
        Mostrar(r);
    }//GEN-LAST:event_buttonMaisMouseClicked

    private void buttonMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenosMouseClicked
        ve = true;
        colocarNumero(" - ");
        tipo = "-";
        Mostrar(r);
    }//GEN-LAST:event_buttonMenosMouseClicked

    private void buttonDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDivisaoMouseClicked
        ve = true;
        colocarNumero(" / ");
        tipo = "/";
        Mostrar(r);
    }//GEN-LAST:event_buttonDivisaoMouseClicked

    private void buttonMultiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMultiplicacaoMouseClicked
        ve = true;
        colocarNumero(" x ");
        tipo = "x";
        Mostrar(r);
    }//GEN-LAST:event_buttonMultiplicacaoMouseClicked

    private void buttonResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResultadoMouseClicked

       r2 = r.split(tipo)[0];
       r3 = r.split(tipo)[1];
       metodo(tipo, r2, r3);
       
       jLabel2.setText(""+r+" =");
       
       r = Double.toString(c.getResultado());
       jTextField1.setText(""+r);
       ve = false;
    }//GEN-LAST:event_buttonResultadoMouseClicked

    private void buttonApagarTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonApagarTextoMouseClicked
       apagarTexto();
       Mostrar(r);
    }//GEN-LAST:event_buttonApagarTextoMouseClicked

    private void buttonapagarTexto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonapagarTexto2MouseClicked
        apagarTexto();
        Mostrar(r);
    }//GEN-LAST:event_buttonapagarTexto2MouseClicked
    
    public void Iniciar(){
        jTextField1.setText("0");
        r = null;
    }
    
    public String Mostrar(String r) {
        if(r != null){
            jTextField1.setText(""+r);
            
        }
        return r;
    }
    
    public void colocarNumero(String v){
        
        if(r == null){
            r = v;
        }
        else{
            if(r.length() < 8 && ve == false && r != "ERRO"){
                r = r + v;
            }
            else if(r.length() <= 8 && ve == true){
                r = r + v;
            }
            else if(ve == true && r != "ERRO"){
                r2 = r.split(tipo)[0];
                r3 = r.split(tipo)[1]; 
               if(r3.length() <= 8 && r != "ERRO"){
                   r = r + v;
               }
               else{
                   r = "ERRO";
               }
            }
        }
        
    }
    
    public void metodo(String tipo, String r2, String r3){
        
        if(tipo == "x"){
            c.multiplicar(r2, r3);
        }else if(tipo == "\\+"){
           c.somar(r2, r3);
        }else if(tipo == "/"){
            c.dividir(r2, r3);
        }else if(tipo == "-"){
            c.subtrair(r2, r3);
        }
    }
    
    public void apagarTexto(){
        if(r != null){
            r =  r.substring (0, r.length() - 1);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button20;
    private java.awt.Button buttonApagarTexto;
    private java.awt.Button buttonApagarTudo;
    private java.awt.Button buttonDivisao;
    private java.awt.Button buttonMais;
    private java.awt.Button buttonMenos;
    private java.awt.Button buttonMultiplicacao;
    private java.awt.Button buttonNum0;
    private java.awt.Button buttonNum1;
    private java.awt.Button buttonNum2;
    private java.awt.Button buttonNum3;
    private java.awt.Button buttonNum4;
    private java.awt.Button buttonNum5;
    private java.awt.Button buttonNum6;
    private java.awt.Button buttonNum7;
    private java.awt.Button buttonNum8;
    private java.awt.Button buttonNum9;
    private java.awt.Button buttonResultado;
    private java.awt.Button buttonVirgula;
    private java.awt.Button buttonapagarTexto2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
